### PR TITLE
Bind re match

### PR DESCRIPTION
**Pull request by gaborcsardi**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
From https://github.com/MangoTheCat/rematch2/pull/13

**Comment by mdlincoln** [comment]
@gaborcsardi Do you think that you will merge this PR? If not, I'll close it and just create a new package for these functions.

**Comment by gaborcsardi** [comment]
YEs! Thanks for reminding me! Could you pls add this to the NEWS, and yourself to `Authors` in `DESCRIPTION`? Thanks!

**Comment by mdlincoln** [comment]
Done! 🎊  (I didn't add a new version number in `NEWS`/`DESCRIPTION` yet - I'll leave that decision up to you)

**Comment by gaborcsardi** [comment]
Yeah, I messed up sg with the version numbers. Thanks!

**Pull request merged**
